### ISSUE TITLE
`get_neighborhood_vectors_axes` and (0, 0, 0)

### ISSUE THREAD

**Issue by AntoineTheb** [scil-vital/dwi_ml#213]
In `dwi_ml.data.space.neighborhood`, the docstring of the function `get_neighborhood_vectors_axes` mentions that the (0, 0, 0) "neighbour" is returned as well. However, from reading the function, I do not see how it could be. Is this a bug or am I reading it wrong ?

**Comment by EmmaRenauld** [comment]
Line 65: 

    neighborhood_vectors = torch.cat((torch.zeros(1, 3),
                                                                    neighborhood_vectors))

**Comment by EmmaRenauld** [comment]
But I agree the sub-functions do not return it. I'll change that.

**Comment by AntoineTheb** [comment]
Thanks !
